fallback-grpc-addr: 127.0.0.1:3030
dial-grpc-timeout: 10

jaeger:
  url: "http://192.168.192.131:14268/api/traces"

consul:
  addr: 127.0.0.1:8500
order:
  service-name: order
  server-to-run: http
  http-addr: 192.168.192.131:8282
  grpc-addr: 192.168.192.131:5002
stock:
  service-name: stock
  server-to-run: grpc
  grpc-addr: 192.168.192.131:5003
payment:
  service-name: payment
  server-to-run: http
  http-addr: 192.168.192.131:8284
  grpc-addr: 192.168.192.131:5004

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"
